"$schema" = 'https://starship.rs/config-schema.json'

format = """
[î‚¶](blue)\
$os\
$username\
$sudo\
[î‚°](fg:blue bg:none)\
$hostname\
$localip\
[îƒ—](fg:green bg:none)\
$directory\
[î‚°](fg:green bg:none)\
$git_branch\
$git_status\
$status\
$cmd_duration\
$fill\
[î‚¶](fg:orange bg:none)\
$c\
$rust\
$golang\
$nodejs\
$lua\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
$time\
[î‚´ ](fg:gray bg:none)\
$line_break$character"""
palette = 'vscode_black'
[palettes.vscode_black]
white = '#eeeeee'
darkgray = '#111111'
gray = '#2d2d2d'
lightgray = '#44475a'
blue = '#2369d1'
aqua = '#29b8db'
green = '#23d18b'
orange = '#d16923'
purple = '#5723d1'
red = '#D13D23'
yellow = '#f5f543'

[os]
disabled = false
style = "bg:blue fg:white"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
EndeavourOS = "ï†—"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"
Pop = "ïŒª"

[username]
show_always = true
style_user = "bg:blue fg:white"
style_root = "bg:blue fg:white"
format = '[ $user ]($style)'

[sudo]
style = "bg:blue fg:white"
disabled = true

[hostname]
ssh_only = true
style = "fg:white bold bg:red"
ssh_symbol = 'ğŸŒ'
#trim_at = '.companyname.com'
disabled = false
format = '[îƒ—](fg:red bg:none)[ $ssh_symbolğŸŒ$hostname]($style)'

[localip]
ssh_only = true
style = "fg:white bold bg:red"
format = '[ $localipv4 ](fg:white bg:red)[î‚°](fg:red bg:none)'
disabled = false

[directory]
style = "fg:darkgray bg:green"
format = "[ $path ]($style)"
home_symbol = 'î˜— ~'
truncation_length = 2
truncation_symbol = "â€¦/"
truncate_to_repo = true
repo_root_format = '[ ï‚› ](fg:darkgray bg:green)[$read_only]($read_only_style)[$before_root_path]($style)[$repo_root]($style)[$path ]($style)'
repo_root_style = 'fg:primt bold bg:prim'

[directory.substitutions]
".config" = ".ï€“ "
"Developer" = "ó°²‹ "
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Videos" = "ó°¨œ "
"Games" = "ğŸ® "
"steam" = "ï†¶ "
"Emulators" = "ğŸ•¹ï¸ "

[git_branch]
symbol = "ï˜"
style = "bg:purple"
format = '[îƒ—](fg:purple bg:none)[[ $symbol $branch(:$remote_branch) ](fg:white bg:purple)]($style)'

[git_status]
style = "bg:purple"
format = '[[($all_status $ahead_behind)](fg:white bg:purple)]($style)[î‚°](fg:purple bg:none)'

[nodejs]
symbol = "îœ˜"
style = "bg:orange"
format = '[[ $symbol( $version) ](fg:white bg:orange)]($style)'

[lua]
style = "bg:purple"

[c]
symbol = "î˜ "
style = "bg:orange"
format = '[[ $symbol( $version) ](fg:white bg:orange)]($style)'

[rust]
symbol = "î¨"
style = "bg:orange"
format = '[[ $symbol( $version) ](fg:white bg:orange)]($style)'

[golang]
symbol = "î˜§"
style = "bg:orange"
format = '[[ $symbol( $version) ](fg:white bg:orange)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:orange"
format = '[[ $symbol( $version) ](fg:white bg:orange)]($style)'

[java]
symbol = "î‰–"
style = "bg:orange"
format = '[[ $symbol( $version) ](fg:white bg:orange)]($style)'

[kotlin]
symbol = "î˜´"
style = "bg:orange"
format = '[[ $symbol( $version) ](fg:white bg:orange)]($style)'

[haskell]
symbol = "î˜Ÿ"
style = "bg:orange"
format = '[[ $symbol( $version) ](fg:white bg:orange)]($style)'

[python]
symbol = "î˜†"
style = "bg:orange"
format = '[[ $symbol( $version) ](fg:white bg:orange)]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:lightgray"
format = '[[ $symbol( $context) ](fg:white bg:red)]($style)'

[conda]
style = "bg:lightgray"
format = '[[ $symbol( $environment) ](fg:white bg:red)]($style)'

[time]
disabled = false
time_format = " %I:%M%P"
style = "bg:gray"
format = '[[ ïº $time ](fg:white bg:gray)]($style)'

[fill]
symbol = " "

[cmd_duration]
style = "fg:yellow bg:none"
format = '[îƒ—]($style)[ $duration ]($style inverted)[î‚´]($style)'
min_time = 500
disabled = false

[status]
format = '[$symbol]($style)'
style = 'fg:sudo bg:prim'
symbol = ' ïª '

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[â¯](bold green)'
error_symbol = '[â¯](bold red)'
vimcmd_symbol = '[ï´](bold green)'
vimcmd_replace_one_symbol = '[R](bold purple)'
vimcmd_replace_symbol = '[R](bold purple)'
vimcmd_visual_symbol = '[V](bold yellow)'
