"$schema" = 'https://starship.rs/config-schema.json'

format = """
[â•­](lightgray)[î‚¶](blue)$os$username$sudo[î‚°](fg:blue)\
$hostname$localip\
[îƒ—](fg:green)$directory[î‚°](fg:green)\
$git_branch$git_status\
$cmd_duration\
$status\
$fill\
$c$rust$golang$nodejs$lua$php$java$kotlin$haskell$python\
$docker_context$conda\
[î‚¶](fg:gray bg:none)$time[î‚´](fg:gray bg:none)\
[ ](fg: none bg: none)$line_break\
[â•°â”€](fg:lightgray)$character\
"""

palette = 'vscode_black'
[palettes.vscode_black]
white = '#eeeeee'
darkgray = '#111111'
gray = '#2d2d2d'
lightgray = '#44475a'
blue = '#2369d1'
aqua = '#29b8db'
green = '#23d18b'
orange = '#d16923'
purple = '#5723d1'
red = '#D13D23'
yellow = '#f5f543'

#Shapes
# [î‚¶](fg:orange)
# [î‚´](fg:orange)
# [â”€](fg:lightgray)
# [îƒ—](fg:green)
# [î‚°](fg:green)\

[os]
disabled = false
style = "bg:blue fg:white"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
EndeavourOS = "ï†—"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"
Pop = "ïŒª"

[username]
show_always = true
style_user = "bg:blue fg:white"
style_root = "bg:blue fg:white"
format = '[ $user ]($style)'

[sudo]
style = "bg:blue fg:white"
disabled = true

[hostname]
ssh_only = true
style = "fg:white bold bg:red"
ssh_symbol = 'ğŸŒ'
#trim_at = '.companyname.com'
disabled = false
format = '[îƒ—](fg:red bg:none)[ $ssh_symbolğŸŒ$hostname]($style)'

[localip]
ssh_only = true
style = "fg:white bold bg:red"
format = '[ $localipv4 ](fg:white bg:red)[î‚°](fg:red bg:none)'
disabled = false

[directory]
style = "fg:darkgray bg:green"
format = "[ $path ]($style)"
home_symbol = 'î˜— ~'
truncation_length = 2
truncation_symbol = "â€¦/"
truncate_to_repo = true
repo_root_format = '[ ï‚› ](fg:darkgray bg:green)[$read_only]($read_only_style)[$before_root_path]($style)[$repo_root]($style)[$path ]($style)'
repo_root_style = 'fg:primt bold bg:prim'

[directory.substitutions]
".config" = ".ï€“ "
"Developer" = "ó°²‹ "
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Videos" = "ó°¨œ "
"Games" = "ğŸ® "
"steam" = "ï†¶ "
"Emulators" = "ğŸ•¹ï¸ "

[git_branch]
symbol = "ï˜"
style = "bg:purple"
format = '[îƒ—](fg:purple bg:none)[[ $symbol $branch(:$remote_branch) ](fg:white bg:purple)]($style)'

[git_status]
style = "bg:purple"
format = '[[($all_status $ahead_behind)](fg:white bg:purple)]($style)[î‚°](fg:purple bg:none)'

[nodejs]
symbol = 'ó°™ Node'
style = "bg:orange"
format = '[î‚¶](fg:orange)[[ $symbol( $version) ](fg:white bg:orange)]($style)[î‚´](fg:orange)[â”€](fg:lightgray)'

[lua]
style = "bg:purple"

[c]
symbol = "î˜ C"
style = "bg:orange"
format = '[î‚¶](fg:orange)[[ $symbol( $version) ](fg:white bg:orange)]($style)[î‚´](fg:orange)[â”€](fg:lightgray)'

[rust]
symbol = "î¨ Rust"
style = "bg:orange"
format = '[î‚¶](fg:orange)[[ $symbol( $version) ](fg:white bg:orange)]($style)[î‚´](fg:orange)[â”€](fg:lightgray)'

[golang]
symbol = "î˜§ Go"
style = "bg:orange"
format = '[î‚¶](fg:orange)[[ $symbol( $version) ](fg:white bg:orange)]($style)[î‚´](fg:orange)[â”€](fg:lightgray)'

[php]
symbol = "î˜ˆ Php"
style = "bg:orange"
format = '[î‚¶](fg:orange)[[ $symbol( $version) ](fg:white bg:orange)]($style)[î‚´](fg:orange)[â”€](fg:lightgray)'

[java]
symbol = 'îœ¸ Java'
style = "bg:orange"
format = '[î‚¶](fg:orange)[[ $symbol( $version) ](fg:white bg:orange)]($style)[î‚´](fg:orange)[â”€](fg:lightgray)'

[kotlin]
symbol = "î˜´ Kotlin"
style = "bg:orange"
format = '[î‚¶](fg:orange)[[ $symbol( $version) ](fg:white bg:orange)]($style)[î‚´](fg:orange)[â”€](fg:lightgray)'

[haskell]
symbol = "î˜Ÿ Haskell"
style = "bg:orange"
format = '[î‚¶](fg:orange)[[ $symbol( $version) ](fg:white bg:orange)]($style)[î‚´](fg:orange)[â”€](fg:lightgray)'

[python]
symbol = 'îœ¼ Python'
style = "bg:orange"
format = '[î‚¶](fg:orange)[[ $symbol( $version) ](fg:white bg:orange)]($style)[î‚´](fg:orange)[â”€](fg:lightgray)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:lightgray"
format = '[î‚¶](fg:red)[[ $symbol( $context) ](fg:white bg:red)]($style)[î‚´](fg:red)[â”€](fg:lightgray)'

[conda]
style = "bg:lightgray"
format = '[î‚¶](fg:red)[[ $symbol( $environment) ](fg:white bg:red)]($style)[î‚´](fg:red)[â”€](fg:lightgray)'

[time]
disabled = false
time_format = " %I:%M%P"
style = "bg:gray"
format = '[[ ïº $time ](fg:white bg:gray)]($style)'

[fill]
symbol = " "

[cmd_duration]
style = "fg:yellow bg:none"
format = '[îƒ—]($style)[ ó±‹ $duration ]($style inverted)[î‚´]($style)'
min_time = 500
disabled = false

[status]
style = "fg:red bg:none"
disabled = false
format = '[â”€](fg:lightgray bg:none)[î‚¶](fg:red bg:none)[$symbol ](fg:white bg:red)[î‚´]($style)'
symbol = ' ïª  Error'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[â¯](bold green)'
error_symbol = '[â¯](bold red)'
vimcmd_symbol = '[ï´](bold green)'
vimcmd_replace_one_symbol = '[R](bold purple)'
vimcmd_replace_symbol = '[R](bold purple)'
vimcmd_visual_symbol = '[V](bold yellow)'
