# yazi/.config/yazi/yazi.toml
[opener]
edit = [
  { run = '/usr/bin/nvim "$@"', block = true, desc = "NeoVim", for = "unix" },
]
image-edit = [
  { run = 'gimp "$@"', block = true, desc = "Gimp", for = "unix" },
  { run = 'inkscape "$@"', block = true, desc = "Inkscape", for = "unix" },
]
install-rpm = [
  { run = "sh -lc 'sudo dnf -y install \"$1\"' -- \"$@\"", block = true, desc = "DNF Install (sudo)", for = "unix" },
]
video = [{ run = 'vlc "$@"', orphan = true, desc = "VLC", for = "unix" }]
pdf = [{ run = 'okular "$@"', orphan = true, desc = "Okular", for = "unix" }]
open = [
  { run = 'xdg-open "$@"', desc = "Open" },
  { run = '/usr/bin/nvim "$@"', block = true, desc = "NeoVim", for = "unix" },
  { run = 'vim "$@"', block = true, desc = "Vim", for = "unix" },
  { run = 'gimp "$@"', block = true, desc = "Gimp", for = "unix" },
  { run = 'inkscape "$@"', block = true, desc = "Inkscape", for = "unix" },
]

[open]
prepend_rules = [
  { url = "*.rpm", use = "install-rpm" },
  { mime = "image/*", use = "image-edit" },
  { mime = "video/*", use = "video" },
  { mime = "application/pdf", use = "pdf" },
]

[plugin]
prepend_preloaders = [
  # Do not preload files in mounted locations:
  # Environment variable won't work here.
  # Using absolute path instead.
  { name = "/run/user/1000/gvfs/**/*", run = "noop" },

  # For mounted location for hard disk/drive
  { name = "/run/media/USER/**/*", run = "noop" },
  { name = "~/mnt/*", run = "noop" },
  #... the rest of preloaders
]
prepend_previewers = [
  # Allow to preview folder.
  { name = "*/", run = "folder", sync = true },
  # Do not previewing files in mounted locations (uncomment to except text file):
  # { mime = "{text/*,application/x-subrip}", run = "code" },
  # Using absolute path.
  { name = "/run/user/1000/gvfs/**/*", run = "noop" },
  { name = "~/mnt/*", run = "noop" },

  # For mounted hard disk.
  { name = "/run/media/USER/**/*", run = "noop" },
  #... the rest of previewers
]
prepend_fetchers = [
  { id = "git", name = "*", run = "git" },
  { id = "git", name = "*/", run = "git" },
]
